version: '3.8'
services:

  # Main Application (Nginx + PHP)
  app:
    image: ghcr.io/rajendra371/minnanotakahashi:latest
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "80:80"
      - "3006:3006"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: prod
    volumes:
      - ./storage:/var/www/storage
    depends_on:
      - mysql

  # Node Service for Local Development Only
  node:
    image: node:14
    container_name: laravel-node
    working_dir: /app
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - app-code:/var/www:ro
    command: npm run watch
    profiles:
      - dev

  # Database Service
  mysql:
    image: mysql:5.7
    container_name: laravel-mysql
    restart: unless-stopped
    command: --sql-mode=""
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local
  app-code:
    driver: local
