version: '3.8'
services:

  # Main Application (Nginx + PHP)
  app:
    image: ghcr.io/rajendra371/minnanotakahashi:latest
    container_name: laravel-app
    restart: unless-stopped
    expose:
      - "80"
      - "3006"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: prod
    volumes:
      - ./storage:/var/www/storage
    depends_on:
      - db
    links:
      - db

  # Node Service (Local Dev Only)
  node:
    image: node:14
    container_name: laravel-node
    profiles: [dev]
    volumes:
      - ./:/app

  # Database Service
  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    command: --sql-mode=""
    tty: true
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local
