version: '3.8'
services:

  # Nginx Service (Entry Point)
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "3006:3006"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - app-code:/var/www:ro
    networks:
      - app-network
    depends_on:
      - app

  # PHP Application
  app:
    image: ghcr.io/rajendra371/minnanotakahashi:latest
    container_name: laravel-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    entrypoint: sh -c "cp -rp /var/www/. /app-data/ && php-fpm"
    volumes:
      - app-code:/app-data
      - /var/www/vendor
      - ./storage:/var/www/storage
    networks:
      - app-network

  # Node Service for Frontend Watcher
  node:
    image: node:14
    container_name: laravel-node
    working_dir: /app
    volumes:
      - ./:/app
    command: npm run watch
    networks:
      - app-network

  # Database Service
  db:
    image: mysql:5.7
    container_name: laravel-db
    restart: unless-stopped
    command: --sql-mode=""
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  app-code:
    driver: local
